// Generated by BUCKLESCRIPT VERSION 1.9.0, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/reasonReact.js");
var GatsbyLink  = require("gatsby-link");

function make(to_, children) {
  return ReasonReact.wrapJsForReason(GatsbyLink.default, {
              to: to_
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
